### ISSUE TITLE
Open recent files in welcome screen

### ISSUE THREAD

**Issue by ryonakano** [elework/Spreadsheet#56]

**Comment by aleksandar-stefanovic** [comment]
Would the outline of the solution be as follows?:

1. Create a GSchema with a `recent-files` setting, which would be a string array, or something similar
2. When opening or saving files, add the file to the set of recent files, optionally discarding the oldest file, so that the set is limited in size
3. When opening the application, display the recent files alongside other options

**Comment by ryonakano** [comment]
Yes, exactlly. FYI, I imagine the following function that Spice-Up has:

![Screenshot from 2019-12-29 19-54-05](https://user-images.githubusercontent.com/26003928/71555952-32338980-2a75-11ea-8be0-68c44932f126.png)

**Comment by aleksandar-stefanovic** [comment]
Alright, I will open an ongoing pull request as soon as I make some progress

**Comment by aleksandar-stefanovic** [comment]
Should there be an unlimited list of recent files, or should we limit it to some specific number? This is more of an UX-design question, rather than a technical question, since it really doesn't have any performance impact. On one hand, if we limit it to a number too low, e.g. 5, user will often need a document that is not on that list, which defeats the purpose of recent files. If we set the list size to some big number (e.g. 50), or unlimited, clutter may occur in the GUI, which can be confusing to the user.

I guess it comes down to the type of an application we are trying to create. If it's intended to be "The Only True Way" of editing spreadsheets, it makes more sense to have an unlimited list, since in that case, it also has a role of a "file browser", or a "spreadsheet browser" if you will. Otherwise, if it doesn't have that major of an responsibility, it is okay to have a limited list of items, to reduce GUI complexity (from an UX standpoint).

**Comment by aleksandar-stefanovic** [comment]
Also, I've noticed that there was an commented-out line in the Welcome screen, which does this:

![recent file option](https://imgur.com/QRtAdTH.png)



Do we keep the most recent file here, or do we list all of the recent files in a separate list, like in Spice-Up?

**Comment by ryonakano** [comment]
Hmm, I feel keeping a limited number of recent files like 10 or 15 would even make more sense because I guess perhaps we can't keep remembering a file that we opened 20 or 30 times ago. :thinking:

And, I feel the design of the "Open Last File" menu in the old Welcome screen might not be useful very much (although it fits the looks of other menu items really nicely) because they can only sustain one (the last) file. People who want to open files that they used a couple of times ago might feel uncomfortable. So I personally think to list recent files in a separate list like in Spice-Up.

**Comment by aleksandar-stefanovic** [comment]
So far, I've came up with this:

![Screenshot from 2019-12-30 10 48 32](https://user-images.githubusercontent.com/6058082/71576723-df4be780-2af1-11ea-86e7-8439550943fc.png)

What do you generally think? I've reused some of the `Granite.Widgets.Welcome` components (we can also just completely reuse the Welcome widget for this scenario). Of course, this is not final design, but I'm unsure where to go from here...

**Comment by ryonakano** [comment]
The design looks pretty good. It would be more useful if we could see the path of recent files in the list. IIRC the menu in `Granite.Widget.Welcome` should have an element called `secondary_text`, which also be used in the current welcome screen of Spreadsheet (the text in gray like "Create an empty sheet"), so I think we can use this element to show the path for each recent files.

Maybe we can save the path of recent files in GSettings to show recent files in UI. We can use [`GLib.File.get_basename`](https://valadoc.org/gio-2.0/GLib.File.get_basename.html) to fetch a filename (for primary texts in the list element) and [`GLib.File.get_path`](https://valadoc.org/gio-2.0/GLib.File.get_path.html) to fetch a file path (for secondary texts). I guess we can reuse [these codes](https://github.com/ryonakano/Spreadsheet/blob/1be54ef289ca2364d026c31a8337b430751ea78e/src/App.vala#L57-L61) to open a recent file when a user clicks it.
